@url_dev=http://localhost:3000/api/v1/auth
@mobile_agent=Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.131 Mobile Safari/537.36
@web_agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxYTQ2MzAyNS05NTczLTRmNDktYjViYS03ZmE1NTFjNzBlYTgiLCJyb2xlIjowLCJ2ZXJpZnkiOjAsInVzZXJBZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDYuMTsgV2luNjQ7IHg2NDsgcnY6NDcuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC80Ny4wIiwidG9rZW5fdHlwZSI6MCwiaWF0IjoxNzM1ODA2NDA5LCJleHAiOjE3MzU4MTAwMDl9.dC9m4KlnZrw2JRZffMkfpdWgCvSoD5muu312E90ZHXQ
@refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxYTQ2MzAyNS05NTczLTRmNDktYjViYS03ZmE1NTFjNzBlYTgiLCJyb2xlIjowLCJ2ZXJpZnkiOjAsInVzZXJBZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDYuMTsgV2luNjQ7IHg2NDsgcnY6NDcuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC80Ny4wIiwidG9rZW5fdHlwZSI6MSwiaWF0IjoxNzM1ODA2NDA5LCJleHAiOjE3MzY0MTEyMDl9.y3n124cGMsXtpBSdcWE4qIb3SeG0pz0SidmvtR0_FGw

### login
POST {{url_dev}}/login
User-Agent: {{web_agent}}
Content-Type: application/json

{
    "email": "Linhhuynh1@gmail.com",
    "password": "Linhhuynh@12"
}

### register
POST {{url_dev}}/register
User-Agent: {{web_agent}}
Content-Type: application/json

{
    "email": "Linhhuynh1@gmail.com",
    "username": "Linhhuynh1",
    "password": "Linhhuynh@12",
    "confirmPassword": "Linhhuynh@12"
}

### auth
POST {{url_dev}}/me?platform=mobile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxYTQ2MzAyNS05NTczLTRmNDktYjViYS03ZmE1NTFjNzBlYTgiLCJyb2xlIjowLCJ0eXBlIjowLCJpYXQiOjE3MzU3OTA5NjQsImV4cCI6MTczNTc5NDU2NH0.z7q0n05j8D6IQ9GCB-VQt9i5uV1GSWq4U89NKYMeDGg
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0


### refresh
POST {{url_dev}}/refreshToken
User-Agent: {{web_agent}}
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxYTQ2MzAyNS05NTczLTRmNDktYjViYS03ZmE1NTFjNzBlYTgiLCJyb2xlIjowLCJ2ZXJpZnkiOjAsInVzZXJBZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDYuMTsgV2luNjQ7IHg2NDsgcnY6NDcuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC80Ny4wIiwidG9rZW5fdHlwZSI6MSwiaWF0IjoxNzM1ODA2NDA5LCJleHAiOjE3MzY0MTEyMDl9.y3n124cGMsXtpBSdcWE4qIb3SeG0pz0SidmvtR0_FGw"
}

### logout
POST {{url_dev}}/logout
Authorization: Bearer {{access_token}}
User-Agent: {{web_agent}}
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIxYTQ2MzAyNS05NTczLTRmNDktYjViYS03ZmE1NTFjNzBlYTgiLCJyb2xlIjowLCJ2ZXJpZnkiOjAsInVzZXJBZ2VudCI6Ik1vemlsbGEvNS4wIChXaW5kb3dzIE5UIDYuMTsgV2luNjQ7IHg2NDsgcnY6NDcuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC80Ny4wIiwidG9rZW5fdHlwZSI6MSwiaWF0IjoxNzM1ODA2NDA5LCJleHAiOjE3MzY0MTEyMDl9.y3n124cGMsXtpBSdcWE4qIb3SeG0pz0SidmvtR0_FGw"
}

### verify-mail
POST {{url_dev}}/verify-email
User-Agent: {{web_agent}}
Content-Type: application/json

{
    "verify_email_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI4M2QwZjM0MS05Mjc3LTQyNjAtYjFkYS0yZGZiZWRiMDg2YmEiLCJyb2xlIjowLCJ2ZXJpZnkiOjAsInVzZXJfYWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCA2LjE7IFdpbjY0OyB4NjQ7IHJ2OjQ3LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNDcuMCIsInRva2VuX3R5cGUiOjMsImlhdCI6MTczNTk4ODkzNSwiZXhwIjoxNzM1OTg4OTk1fQ.RQHGFknajOT5sI7my2XBhv0sm-gUbbmWsiwZF37RUZk",
    "code": "601598"
}

### resend-verify-mail
POST {{url_dev}}/resend-verify-email
User-Agent: {{web_agent}}
Content-Type: application/json

{
    "verify_email_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJkMDNmYThjOC1jZmQ3LTQ4Y2MtODFiZi1mNDE4YTNmMDI2ZTAiLCJ2ZXJpZnkiOjAsInVzZXJfYWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCA2LjE7IFdpbjY0OyB4NjQ7IHJ2OjQ3LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNDcuMCIsInRva2VuX3R5cGUiOjMsImlhdCI6MTczNTk4OTUxOCwiZXhwIjoxNzM1OTg5NTc4fQ.U8ljylzS86wM6RA4a-Msp-tscvl5U62ZONegz9JbyKk"
}