@url_dev=http://localhost:3000/api/v1/users
@mobile_agent=Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.131 Mobile Safari/537.36
@web_agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1MWM2ZmYyNi00M2E5LTQ1NDAtODM2My1iN2RmMDBkMDNkNTciLCJyb2xlIjowLCJ2ZXJpZnkiOjAsInVzZXJfYWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCA2LjE7IFdpbjY0OyB4NjQ7IHJ2OjQ3LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNDcuMCIsInRva2VuX3R5cGUiOjAsImlhdCI6MTczNjE0NjA3NSwiZXhwIjoxNzM2MTQ5Njc1fQ.T-zLi88IvXTWTRu8VDMAr2Zwshetm0ABeCc4XYpQFEI
@refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1MWM2ZmYyNi00M2E5LTQ1NDAtODM2My1iN2RmMDBkMDNkNTciLCJyb2xlIjowLCJ2ZXJpZnkiOjAsInVzZXJfYWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCA2LjE7IFdpbjY0OyB4NjQ7IHJ2OjQ3LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNDcuMCIsInRva2VuX3R5cGUiOjEsImlhdCI6MTczNjE0NjA3NSwiZXhwIjoxNzM2NzUwODc1fQ.oog9ypE73fnZu9keIdvs6hD2SJSVPDSdgfa5eRRaNK4

### get profile
GET {{url_dev}}/profile
User-Agent: {{web_agent}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
}
