@url_dev=http://localhost:3000/api/v1/users
@mobile_agent=Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.5735.131 Mobile Safari/537.36
@web_agent=Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJjOWVhNzhiYi04NWM0LTRjMDktYTc1Ni1kMDcwMjVhNmY4YzgiLCJyb2xlIjoxLCJ2ZXJpZnkiOjEsInVzZXJfYWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCA2LjE7IFdpbjY0OyB4NjQ7IHJ2OjQ3LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNDcuMCIsInRva2VuX3R5cGUiOjAsImlhdCI6MTczNzIxMzQ0NywiZXhwIjoxNzM3MjE3MDQ3fQ.6yUug1NE-dSyz4moDN7iS7-8YXCrijwL0MXfMlnqABs
@refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJjOWVhNzhiYi04NWM0LTRjMDktYTc1Ni1kMDcwMjVhNmY4YzgiLCJyb2xlIjowLCJ2ZXJpZnkiOjAsInVzZXJfYWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCA2LjE7IFdpbjY0OyB4NjQ7IHJ2OjQ3LjApIEdlY2tvLzIwMTAwMTAxIEZpcmVmb3gvNDcuMCIsInRva2VuX3R5cGUiOjEsImlhdCI6MTczNzIxMTYzNywiZXhwIjoxNzM3ODE2NDM3fQ.2Prf2t_gEOtS1gKIuTbYwGikc4wd3ne7YVpyeP51UkI

### get profile
GET {{url_dev}}/profile
User-Agent: {{web_agent}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
}

### get profile by id
GET {{url_dev}}/profile/409588b5-0606-4261-9475-1ecbdfe11d7f
User-Agent: {{web_agent}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
}

### get all profiles
GET {{url_dev}}/profile/all
User-Agent: {{web_agent}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
}

### update profile
PATCH {{url_dev}}/update_profile
User-Agent: {{web_agent}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "gender": 2
}
