openapi: 3.0.3
info:
    title: Swagger Shopee - OpenAPI 3.0
    description: |-

    termsOfService: http://swagger.io/terms/
    contact:
        email: apiteam@swagger.io
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    version: 1.0.11
externalDocs:
    description: Find out more about Swagger
    url: http://swagger.io
servers:
    - url: http://localhost:3000/api/v1
tags:
    - name: auth
      description: Xác minh và xác thực
    - name: users
      description: Người dùng
paths:
#   AUTH ROUTES
    /auth/login:
        $ref: "./resources/auth/login.yaml"
    /auth/logout:
        $ref: "./resources/auth/logout.yaml"
    /auth/register:
        $ref: "./resources/auth/register.yaml"
    /auth/refresh-token:
        $ref: "./resources/auth/refreshToken.yaml"
    /auth/verify-email:
        $ref: "./resources/auth/verifyEmail.yaml"
    /auth/resend-verify-email:
        $ref: "./resources/auth/resendVerifyEmail.yaml"
    /auth/forgot-password:
        $ref: "./resources/auth/forgotPassword.yaml"
    /auth/verify-password:
        $ref: "./resources/auth/verifyPassword.yaml"
    /auth/resend-verify-password:
        $ref: "./resources/auth/resendVerifyPassword.yaml"
    /auth/reset-password:
        $ref: "./resources/auth/resetPassword.yaml"

#   USERS ROUTES
    /users/profile:
        $ref: "./resources/users/profile.yaml"


components:
    # parameters:
    #     $ref: "./parameters/_index.yaml"
    schemas:
        $ref: "./schemas/_index.yaml"
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
