openapi: 3.0.3
info:
  title: Swagger Shopee - OpenAPI 3.0
  description: ''
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: 'http://localhost:3000/api/v1'
tags:
  - name: auth
    description: Xác minh và xác thực
  - name: users
    description: Người dùng
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Đăng nhập
      description: Đăng nhập
      operationId: login
      parameters:
        - in: query
          name: platform
          schema:
            type: string
          required: true
          description: 'phân biệt thiết bị (web, mobile)'
          example: web
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Login success
                  result:
                    $ref: '#/components/schemas/SuccessAuthenticate'
        '400':
          description: Nền tảng không hợp lệ
        '422':
          description: Sai các trường thông tin
  /auth/logout:
    post:
      tags:
        - auth
      summary: Đăng xuất
      description: Đăng xuất
      operationId: logout
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutBody'
      responses:
        '200':
          description: Đăng xuất thành công
        '400':
          description: Nền tảng không hợp lệ
        '401':
          description: Token không hợp lệ
        '404':
          description: Người dùng không tồn tại
        '422':
          description: Sai các trường thông tin
  /auth/register:
    post:
      tags:
        - auth
      summary: Đăng ký tài khoản
      description: ''
      operationId: register
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBody'
      responses:
        '200':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Register success
                  result:
                    $ref: '#/components/schemas/SuccessAuthenticate'
        '400':
          description: Nền tảng không hợp lệ
        '422':
          description: Sai các trường thông tin
  /auth/refresh-token:
    post:
      tags:
        - auth
      summary: Refresh Token
      description: Refresh Token
      operationId: refresh_token
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutBody'
      responses:
        '200':
          description: Refresh thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Login success
                  result:
                    $ref: '#/components/schemas/SuccessAuthenticate'
        '400':
          description: Nền tảng không hợp lệ
        '401':
          description: Token không hợp lệ
        '422':
          description: Sai các trường thông tin
  /auth/verify-email:
    post:
      tags:
        - auth
      summary: Xác thực mail
      description: Gửi verify_email_token và code lên server
      operationId: verify_email
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                verify_email_token:
                  type: string
                code:
                  type: string
                  example: '123456'
              required:
                - verify_email_token
                - code
      responses:
        '200':
          description: Xác thực email thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                  result:
                    $ref: '#/components/schemas/SuccessAuthenticate'
        '400':
          description: Sai code
        '422':
          description: Sai các trường thông tin
  /auth/resend-verify-email:
    post:
      tags:
        - auth
      summary: Yêu cầu gửi lại mã otp
      description: 'Gửi verify_email_token cũ lên server, trả token mới'
      operationId: resend_verify_email
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                verify_email_token:
                  type: string
              required:
                - verify_email_token
      responses:
        '200':
          description: Gửi email thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  verify_email_token:
                    type: string
        '400':
          description: null
        '422':
          description: Sai các trường thông tin
  /auth/forgot-password:
    post:
      tags:
        - auth
      summary: Quên mật khẩu
      description: 'Gửi username hoặc email lên server, trả lại forgot_password_token'
      operationId: forgot_password
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: linh1234
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: object
                properties:
                  forgot_password_token:
                    type: string
        '400':
          description: null
        '422':
          description: Sai các trường thông tin
  /auth/verify-password:
    post:
      tags:
        - auth
      summary: Xác thực OTP quên mật khẩu
      description: 'Gửi forgot_password_token và otp code lên server, trả lại forgot_password_token mới'
      operationId: verify_password
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                forgot_password_token:
                  type: string
                code:
                  type: string
                  example: '123456'
              required:
                - forgot_password_token
                - code
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: object
                properties:
                  forgot_password_token:
                    type: string
        '400':
          description: null
        '422':
          description: Sai các trường thông tin
  /auth/resend-verify-password:
    post:
      tags:
        - auth
      summary: Gửi lại OTP quên mật khẩu
      description: 'Gửi forgot_password_token cũ lên server, trả lại forgot_password_token mới'
      operationId: resend_verify_password
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                forgot_password_token:
                  type: string
              required:
                - forgot_password_token
      responses:
        '200':
          description: null
          content:
            application/json:
              schema:
                type: object
                properties:
                  forgot_password_token:
                    type: string
        '400':
          description: null
        '422':
          description: Sai các trường thông tin
  /auth/reset-password:
    post:
      tags:
        - auth
      summary: Đổi mật khẩu mới
      description: Gửi forgot_password_token và mật khẩu mới lên server
      operationId: reset_password
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                forgot_password_token:
                  type: string
                password:
                  type: string
                  example: Linhhoccode$123
              required:
                - forgot_password_token
                - password
      responses:
        '200':
          description: null
        '400':
          description: null
        '422':
          description: Sai các trường thông tin
  /users/profile:
    get:
      tags:
        - users
      summary: Lấy thông tin người dùng
      description: Gửi access_token
      operationId: user_profile
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      responses:
        '200':
          description: null
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true
              message:
                type: string
              result:
                $ref: '#/components/schemas/User'
        '400':
          description: null
        '422':
          description: Sai các trường thông tin
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
          example: linh1234
        email:
          type: string
          example: linh1234@gmail.com
        nickname:
          type: string
        dob:
          type: ISO string
        gender:
          type: number
          description: '1 là nam, 2 là nữ, 3 là khác'
        avatar:
          type: url
        phone:
          type: string
      required:
        - password
    RegisterBody:
      type: object
      properties:
        username:
          type: string
          example: linh1234
        email:
          type: string
          format: email
          example: linhdeptrai@gmail.com
        password:
          type: string
          example: Linhhoccode$123
        confirmPassword:
          type: string
          example: Linhhoccode$123
      required:
        - username
        - email
        - password
        - confirmPassword
    LoginBody:
      type: object
      properties:
        username:
          type: string
          example: linh1234
        email:
          type: string
          example: linh1234@gmail.com
        password:
          type: string
          example: Linhhoccode$123
      required:
        - password
    LogoutBody:
      type: object
      properties:
        refresh_token:
          type: string
      required:
        - refresToken
    ApiResponse:
      type: object
      properties:
        message:
          type: string
          example: Get user info successfully
        result:
          type: object
          example:
            id: 1
            name: linh1234
    FailedValidation:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Validation failed
        errors:
          type: object
          example:
            email:
              message: Email already exists
              value: linhhuynh@gmail.com
    SuccessAuthenticate:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiZTBhZDJlNDNkMjQ2NDM5NGZlZWRiIiwidG9rZW5fdHlwZSI6MCwidmVyaWZ5IjoxLCJpYXQiOjE2OTEzODMyMjYsImV4cCI6MTY5MTQ2OTYyNn0.HTLX20cB7_z0c9c8FDg3MIx6RJEELHHlmJNZa94ku-o
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiZTBhZDJlNDNkMjQ2NDM5NGZlZWRiIiwidG9rZW5fdHlwZSI6MSwidmVyaWZ5IjoxLCJpYXQiOjE2OTEzODMyMjYsImV4cCI6MTcwMDAyMzIyNn0.bFnaBfxWl-Q48HCwAeMpNzZwTO9LEjcBd7Zyipjqr64
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
