openapi: 3.0.3
info:
  title: Swagger Shopee - OpenAPI 3.0
  description: ''
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: 'http://localhost:3000/api/v1'
tags:
  - name: auth
    description: Xác minh và xác thực
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: Đăng nhập
      description: Đăng nhập
      operationId: login
      parameters:
        - in: query
          name: platform
          schema:
            type: string
          required: true
          description: 'phân biệt thiết bị (web, mobile)'
          example: mobile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Login success
                  result:
                    $ref: '#/components/schemas/SuccessAuthenticate'
        '400':
          description: Nền tảng không hợp lệ
        '422':
          description: Sai các trường thông tin
  /auth/logout:
    post:
      tags:
        - auth
      summary: Đăng xuất
      description: Đăng xuất
      operationId: logout
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
              required:
                - refresToken
      responses:
        '200':
          description: Đăng xuất thành công
        '400':
          description: Nền tảng không hợp lệ
        '401':
          description: Token không hợp lệ
        '404':
          description: Người dùng không tồn tại
        '422':
          description: Sai các trường thông tin
  /auth/register:
    post:
      tags:
        - auth
      summary: Đăng ký tài khoản
      description: ''
      operationId: register
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBody'
      responses:
        '200':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Register success
                  result:
                    $ref: '#/components/schemas/SuccessAuthenticate'
        '400':
          description: Nền tảng không hợp lệ
        '422':
          description: Sai các trường thông tin
  /auth/refreshToken:
    post:
      tags:
        - auth
      summary: Refresh Token
      description: Refresh Token
      operationId: refresh_token
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/paths/~1auth~1login/post/parameters/0'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/paths/~1auth~1logout/post/requestBody/content/application~1json/schema'
      responses:
        '200':
          description: Refresh thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Login success
                  result:
                    $ref: '#/components/schemas/SuccessAuthenticate'
        '400':
          description: Nền tảng không hợp lệ
        '401':
          description: Token không hợp lệ
        '422':
          description: Sai các trường thông tin
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    RegisterBody:
      type: object
      properties:
        username:
          type: string
          example: linh1234
        email:
          type: string
          format: email
          example: linhdeptrai@gmail.com
        password:
          type: string
          example: Linhhoccode$123
        confirmPassword:
          type: string
          example: Linhhoccode$123
      required:
        - username
        - email
        - password
        - confirmPassword
    LoginBody:
      type: object
      properties:
        username:
          type: string
          example: linh1234
        email:
          type: string
          example: linh1234@gmail.com
        password:
          type: string
          example: Linhhoccode$123
      required:
        - password
    ApiResponse:
      type: object
      properties:
        message:
          type: string
          example: Get user info successfully
        result:
          type: object
          example:
            id: 1
            name: linh1234
    FailedValidation:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Validation failed
        errors:
          type: object
          example:
            email:
              message: Email already exists
              value: linhhuynh@gmail.com
    SuccessAuthenticate:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiZTBhZDJlNDNkMjQ2NDM5NGZlZWRiIiwidG9rZW5fdHlwZSI6MCwidmVyaWZ5IjoxLCJpYXQiOjE2OTEzODMyMjYsImV4cCI6MTY5MTQ2OTYyNn0.HTLX20cB7_z0c9c8FDg3MIx6RJEELHHlmJNZa94ku-o
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiZTBhZDJlNDNkMjQ2NDM5NGZlZWRiIiwidG9rZW5fdHlwZSI6MSwidmVyaWZ5IjoxLCJpYXQiOjE2OTEzODMyMjYsImV4cCI6MTcwMDAyMzIyNn0.bFnaBfxWl-Q48HCwAeMpNzZwTO9LEjcBd7Zyipjqr64
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
