openapi: 3.0.3
info:
  title: Swagger Shopee - OpenAPI 3.0
  description: ''
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
servers:
  - url: 'http://localhost:3000/api'
tags:
  - name: users
    description: Everything about Users
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
paths:
  /users/login:
    post:
      tags:
        - users
      summary: Đăng nhập
      description: ''
      operationId: users_register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginBody'
      responses:
        '200':
          description: Đăng nhập thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Login success
                  result:
                    $ref: '#/components/schemas/SuccessAuthenticate'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: Validation failed
                  errors:
                    type: object
                    example:
                      email:
                        message: Email or password is incorrect
                        value: linhhh@gmail.com
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
  /users/register:
    post:
      tags:
        - users
      summary: Đăng ký tài khoản
      description: ''
      operationId: users_register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterBody'
      responses:
        '200':
          description: Đăng ký thành công
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Register success
                  result:
                    $ref: '#/components/schemas/SuccessAuthenticate'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedValidation'
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    RegisterBody:
      type: object
      properties:
        username:
          type: string
          example: linh1234
        email:
          type: string
          format: email
          example: linhdeptrai@gmail.com
        password:
          type: string
          example: Linhhoccode$123
        confirmPassword:
          type: string
          example: Linhhoccode$123
      required:
        - username
        - email
        - password
        - confirmPassword
    LoginBody:
      type: object
      properties:
        username:
          type: string
          example: linh1234
        password:
          type: string
          example: Linhhoccode$123
      required:
        - password
    ApiResponse:
      type: object
      properties:
        message:
          type: string
          example: Get user info successfully
        result:
          type: object
          example:
            id: 1
            name: linh1234
    FailedValidation:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
          example: Validation failed
        errors:
          type: object
          example:
            email:
              message: Email already exists
              value: linhhuynh@gmail.com
    SuccessAuthenticate:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiZTBhZDJlNDNkMjQ2NDM5NGZlZWRiIiwidG9rZW5fdHlwZSI6MCwidmVyaWZ5IjoxLCJpYXQiOjE2OTEzODMyMjYsImV4cCI6MTY5MTQ2OTYyNn0.HTLX20cB7_z0c9c8FDg3MIx6RJEELHHlmJNZa94ku-o
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiZTBhZDJlNDNkMjQ2NDM5NGZlZWRiIiwidG9rZW5fdHlwZSI6MSwidmVyaWZ5IjoxLCJpYXQiOjE2OTEzODMyMjYsImV4cCI6MTcwMDAyMzIyNn0.bFnaBfxWl-Q48HCwAeMpNzZwTO9LEjcBd7Zyipjqr64
