--Data cho shippings
INSERT INTO shippings(shipping_channel_id, name, `desc`, created_at, updated_at) VALUES (1, 'Hỏa tốc', '', 1738668901000, 1738668901000);
INSERT INTO shippings(shipping_channel_id, name, `desc`, created_at, updated_at) VALUES (2, 'Nhanh', '', 1738668901000, 1738668901000);
INSERT INTO shippings(shipping_channel_id, name, `desc`, created_at, updated_at) VALUES (3, 'Tiết kiệm', '', 1738668901000, 1738668901000);
INSERT INTO shippings(shipping_channel_id, name, `desc`, created_at, updated_at) VALUES (4, 'Hàng Cồng Kềnh', '', 1738668901000, 1738668901000);
